### ISSUE TITLE
Visualization not working - AttributeError: module 'tensorflow' has no attribute 'compat'

### ISSUE THREAD

**Issue by RuruX** [dolfin-adjoint/pyadjoint#12]
Hi, I was learning from dolfin-adjoint documentations and when it came to manual - visualization, [http://www.dolfin-adjoint.org/en/latest/documentation/debugging.html], there occurred this error:

Traceback (most recent call last):
  File "dolfin-adjoint.py", line 24, in <module>
    tape.visualise()
  File "/Users/ruru/anaconda3/envs/fenics/lib/python3.7/site-packages/pyadjoint/tape.py", line 342, in visualise
    tf.compat.v1.reset_default_graph()
AttributeError: module 'tensorflow' has no attribute 'compat'

**Comment by stephankramer** [comment]
Sounds like you may have the wrong version of tensorflow. Note that the visualisation also doesn't work with the latest versions. What worked for me was:

    pip install tensorflow==1.15.2

**Comment by RuruX** [comment]
Problem solved! Thank you Stephan!

Though I got the warning:
WARNING:tensorflow:From /Users/ruru/anaconda3/envs/fenics/lib/python3.7/site-packages/pyadjoint/tape.py:348: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.
