### ISSUE TITLE
Create PYPI package

### ISSUE THREAD

**Issue by jorgensd** [dolfin-adjoint/pyadjoint#124]
To be able to bundle the new version of dolfin-adjoint on PYPI, I need pyadjoint to be on pypi, as one cannot specify direct repository dependencies. However, pyadjoint is already taken on pypi (https://pypi.org/project/pyadjoint/)

Does anyone have any suggestions for an appropriate PYPI name?
@sebastkm @dham

**Comment by dham** [comment]
How vexing. We should have domain-squatted that earlier.

How about:

pyadjoint-ad

**Comment by jorgensd** [comment]
Im fine with that, will make a pypi project. 
Do you have a pypi username I should add as owner.

**Comment by jorgensd** [comment]
Package available at: https://pypi.org/project/pyadjoint-ad/
Autopublishing workflow at: https://github.com/dolfin-adjoint/pyadjoint/pull/125

**Comment by connorjward** [comment]
@jorgensd I assume that this issue can be closed?
