### ISSUE TITLE
Possible conflicts with UserExpression

### ISSUE THREAD

**Issue by jingyetan** [dolfin-adjoint/pyadjoint#14]
```from __future__ import print_function
from dolfin import *
from dolfin_adjoint import *
from scipy.interpolate import RegularGridInterpolator



class InterpolatedParameter(UserExpression):

    def __init__(self,X,Y,image,**kwargs):
        self.X = X # A numpy array giving the X-spacing of the image
        self.Y = Y # Same for Y
        self.image = image # The image of measured material property
        super().__init__(**kwargs)
    def eval(self,values,x):
        interp_handle = RegularGridInterpolator((self.X,self.Y),self.image)
        values[0] = interp_handle(x)


def interp(mat, V):
    x,y = mat.shape[0], mat.shape[1]
    mat_interp = InterpolatedParameter(np.linspace(1,x,x),np.linspace(1,y,y),mat,degree=1)
    return interpolate(mat_interp,V)


mesh = RectangleMesh(       Point(-3,-2),
                            Point(3, 2),
                            100, 100, diagonal="crossed")

V    = FunctionSpace(mesh, 'CG', 1)

data = np.array([[0,0,0,0,0,0],
                [0,1,1,1,1,0],
                [0,1,1,1,0,0],
                [0,0,0,0,0,0]])

initial_u = interp(data, V)
```

The `interp()` function and the `InterpolatedParameter()` class are set up to interpolate initial condition from a 2-D numpy array.  It worked fine without dolfin-adjoint, now I am attempting to use them alongside with optimization in dolfin-adjoint, I am receiving these following errors:

> Traceback (most recent call last):
>   File "test.py", line 40, in <module>
>     initial_p = interp(data, V)
>   File "test.py", line 25, in interp
>     mat_interp = InterpolatedParameter(np.linspace(1,x,x),np.linspace(1,y,y),mat,degree=1)
>   File "test.py", line 14, in __init__
>     self.X = X # A numpy array giving the X-spacing of the image
>   File "/usr/local/anaconda3/envs/fe_adjoint/lib/python3.8/site-packages/fenics_adjoint/types/expression.py", line 101, in __setattr__
>     if k == "_ad_initialized" or self._ad_initialized is False:
> AttributeError: 'InterpolatedParameter' object has no attribute '_ad_initialized'

I am running both fenics and dolfin-adjoint on version 2019.1.0, under anaconda3 container.   Does anyone know how to modify the code to keep this interpolation work with dolfin-adjoint?  Thank you!

**Comment by sebastkm** [comment]
I think you have to call `super().__init__(**kwargs)` before setting the attributes.

**Comment by jingyetan** [comment]
> I think you have to call `super().__init__(**kwargs)` before setting the attributes.


I just modified the `InterpolatedParameter()` class with your suggestion as follow:
```
class InterpolatedParameter(UserExpression):

    def __init__(self,X,Y,image,**kwargs):
        super().__init__(**kwargs)
        self.X = X # A numpy array giving the X-spacing of the image
        self.Y = Y # Same for Y
        self.image = image # The image of measured material property
    def eval(self,values,x):
        interp_handle = RegularGridInterpolator((self.X,self.Y),self.image)
        values[0] = interp_handle(x)
```

It seems to have moved forward, but now stuck with the backend.interpolate:

> Traceback (most recent call last):
>   File "test.py", line 37, in <module>
>     initial_u = interp(data, V)
>   File "test.py", line 23, in interp
>     return interpolate(mat_interp,V)
>   File "/usr/local/anaconda3/envs/fe_adjoint/lib/python3.8/site-packages/fenics_adjoint/interpolation.py", line 10, in interpolate
>     output = backend.interpolate(*args, **kwargs)
>   File "/usr/local/anaconda3/envs/fe_adjoint/lib/python3.8/site-packages/dolfin/fem/interpolation.py", line 71, in interpolate
>     Pv.interpolate(v._cpp_object)
>   File "/usr/local/anaconda3/envs/fe_adjoint/lib/python3.8/site-packages/dolfin/function/function.py", line 365, in interpolate
>     self._cpp_object.interpolate(u)
>   File "/usr/local/anaconda3/envs/fe_adjoint/lib/python3.8/site-packages/dolfin/function/expression.py", line 53, in wrapped_eval
>     self.user_expression.eval(values, x)
>   File "test.py", line 17, in eval
>     values[0] = interp_handle(x)
>   File "/usr/local/anaconda3/envs/fe_adjoint/lib/python3.8/site-packages/scipy/interpolate/interpolate.py", line 2486, in __call__
>     raise ValueError("One of the requested xi is out of bounds "
> ValueError: One of the requested xi is out of bounds in dimension 0

**Comment by stephankramer** [comment]
I think the error is fairly clear in this case, no? The interpolated mesh location is not within the regular grid that you have defined, in other words your regular grid does not fully overlap your computational mesh. This is also not really dolfin-adjoint related.
Oh, just a further hint you really don't want to define a new RegularGridInterpolator inside `eval` - move that inside the `__init__`.

**Comment by jingyetan** [comment]
> I think the error is fairly clear in this case, no? The interpolated mesh location is not within the regular grid that you have defined, in other words your regular grid does not fully overlap your computational mesh. This is also not really dolfin-adjoint related.
> Oh, just a further hint you really don't want to define a new RegularGridInterpolator inside `eval` - move that inside the `__init__`.

Good catch! It was my made-up example being incorrect!
