### ISSUE TITLE
MixedCheckpointSchedule is not not working for Multisteps solvers

### ISSUE THREAD

**Issue by Ig-dolci** [dolfin-adjoint/pyadjoint#178]
**Description**

Checkpointing is failing for solver with time derivatives of second order for `MixedCheckpointSchedule`

- Steps to reproduce:

Execute `pyadjoint/tests/firedak_adjoint/test_checkpointing_multistep.py` using `MixedCheckpointSchedule`

**Comment by jrmaddison** [comment]
pyadjoint can't currently run a mixed schedule as it doesn't distinguish between forward and adjoint dependencies. I'm not familiar enough with the pyadjoint checkpointing implementation to know if it could run a valid calculation using the schedule, but the logic of identifying forward restart checkpoints and adjoint dependency data checkpoints isn't quite the same.
