### ISSUE TITLE
ipopt missing in singularity image

### ISSUE THREAD

**Issue by jhalverson** [dolfin-adjoint/pyadjoint#20]
I am trying to run the software on an HPC Linux cluster. Singularity must be used in place of Docker for security reasons. The commands below illustrate the problem:

$ singularity pull docker://quay.io/dolfinadjoint/pyadjoint:2019.1.0
$ singularity exec pyadjoint_2019.1.0.sif python3 -c "import ipopt"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ipopt'

Importing the other modules works fine:

from dolfin import *
from dolfin_adjoint import *

I tried using "singularity build" but that also didn't work. Have you seen this before?

Here is some information about our system:

$ singularity --version
singularity version 3.5.2-1.1.sdl7

$ uname -a
Linux della5.princeton.edu 3.10.0-1127.10.1.el7.x86_64 #1 SMP Thu Jun 4 09:27:22 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release 
NAME="Springdale Linux"
VERSION="7.8 (Verona)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.8"
PRETTY_NAME="Springdale Linux 7.8 (Verona)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:springdale:linux:7.8:GA"
HOME_URL="http://springdale.princeton.edu/"
BUG_REPORT_URL="https://springdale.math.ias.edu/"

REDHAT_BUGZILLA_PRODUCT="Springdale Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Springdale Linux"
REDHAT_SUPPORT_PRODUCT_VERSION=7.8

**Comment by sebastkm** [comment]
Hi,

In the 2019.1.0 docker build you import `pyipopt` and not `ipopt`.
You will likely get an error when running `python3 -c "import pyipopt"`, as you need to import fenics first.

**Comment by jhalverson** [comment]
I encounter the following when trying to import pyipopt:

$ singularity exec pyadjoint_2019.1.0.sif python3 -c "from dolfin import *; from dolfin_adjoint import *; import pyipopt"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyipopt/__init__.py", line 16, in <module>
    from pyipoptcore import *
ImportError: libipopt.so.1: cannot open shared object file: No such file or directory


This appears to be solved with the following:

export SINGULARITYENV_LD_LIBRARY_PATH=/.singularity.d/libs:/usr/local/lib
singularity exec pyadjoint_2019.1.0.sif python3 ./stokes-topology.py


With the above, the stokes-topology.py example runs properly. If you agree then please close this issue.  Thank you for the help.
