### ISSUE TITLE
Should the tlm_value setter use the current block-variable instead of the original?

### ISSUE THREAD

**Issue by stephankramer** [dolfin-adjoint/pyadjoint#25]
Consider the following example:
```
from firedrake import *
from firedrake_adjoint import *
mesh = UnitSquareMesh(1,1)
V = FunctionSpace(mesh, "CG", 1)
u = Function(V)
h = Function(V)

h.assign(1.)

u.assign(2.)
u.tlm_value = h

J = assemble(u**2*dx)

tape = get_working_tape()
tape.evaluate_tlm()
print(J.tlm_value)
```
This doesn't work as expected because `u.tlm_value = h` sets the tlm_value of the original block-variable (the state before the assign) which does not contribute to the functional. When setting a tlm_value I think it makes more sense to say that you want the derivative wrt to the current state. This is btw also what the setter of adj_value on overloaded object does.

I can vaguely see the rationale that when `u` gets reused (say in a timestepping procedure) and the user by mistake sets the tlm_value at the end of the model, it _could_ be doing what's intended - however typically there is still an initialisation step of `u` that you don't want included in the replay. The user should just take care when to set the tlm_value - this is exactly the same as when choosing the control.

Re the getter for tlm_value and adj_value: with adj_value it currently uses original_block_variable.adj_value to get as opposed to block_variable.adj_value which is set in the setter. I also think this is confusing actually. Again I can see the rationale, but again I think you still end up with the wrong result if there's an initialisation step and you want to retrieve the adj_value of the state after that initialisation.

**Comment by funsim** [comment]
I agree. @sebastkm is there an easy fix for this?

**Comment by sebastkm** [comment]
The block variable values being accessible through properties of their associated data objects is deprecated. It was used before the introduction of Controls when we assumed that only leaf nodes could be used as controls. We should remove these properties as user interaction with block variables should ideally be through control objects (at least that was my intention, feel free to suggest better designs).On 29 Jun 2020 09:47, Simon Wolfgang Funke <notifications@github.com> wrote:
I agree. @sebastkm is there an easy fix for this?

**Comment by stephankramer** [comment]
Agreed - access through the control is a much better interface. I don't actually use the tangent linear, I was just getting confused about the behaviour of some of the tests, where tlm_value is accessed through the overloaded object setter/getter all over the place. Let's just get rid of it then.
