### ISSUE TITLE
Running Singularity image with MPI

### ISSUE THREAD

**Issue by jhalverson** [dolfin-adjoint/pyadjoint#26]
I have created a Singularity image from the Docker image:

singularity pull docker://quay.io/dolfinadjoint/pyadjoint:2019.1.0

I now want to run an example in parallel using MPI and Slurm. Here is my Slurm script:

#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --time=01:00:00

export SINGULARITYENV_LD_LIBRARY_PATH=/.singularity.d/libs:/usr/local/lib
srun -n 4 singularity exec pyadjoint_2019.1.0.sif python3 stokes-topology.py

However, I find that the example script is ran four times serially instead of once with the work divided among the processors. When I load an Open MPI module in the Slurm script, the code hangs but MPI.comm_world is 4 instead of 1 (as in the previous case).

stokes-topology.py uses mpi4py. Can someone tell me which MPI implementation is used for building mpi4py? I've looked at the dockerfile but it is not clear to me. We do not have MPICH on our cluster.

**Comment by sebastkm** [comment]
As far as I know, to run applications on singularity with MPI you need to make sure the container and host MPI builds are compatible. I think the pyadjoint:2019.1.0 docker container uses MPICH.

I briefly tested singularity & MPI on a HPC cluster a while ago, but I was unsuccessful. So sadly I can't provide much help on this topic.

You may try something similar to what is described in this guide if you haven't already:
https://sylabs.io/guides/3.3/user-guide/mpi.html
