### ISSUE TITLE
Is the compute_adjoint function not available in dolfin-adjoint?

### ISSUE THREAD

**Issue by pkhunphakdee** [dolfin-adjoint/pyadjoint#28]
Dear everyone,

I am starting to use the dolfin-adjoint to perform a sensitivity analysis. I am currently use the latest docker image (quay.io/dolfinadjoint/pyadjoint:latest). However, there is an error when I am trying to compute the adjoint variable of the problem.
The error message is "name 'compute_adjoint' is not defined". Is this function no longer defined in dolfin-adjoint? If so, is there any alternative way to calculate the adjoint variable?

Sincerely yours
Phuris

**Comment by sebastkm** [comment]
In the master branch, you can look at the following example:
https://github.com/dolfin-adjoint/pyadjoint/blob/master/tests/fenics_adjoint/test_adjoint_state_cb.py

There is also an open PR with a driver for this: PR #17

**Comment by pkhunphakdee** [comment]
Dear Sebastian
Thank you very much for the direction
