### ISSUE TITLE
Modify test rtol

### ISSUE THREAD

**Issue by wence-** [dolfin-adjoint/pyadjoint#30]
I'm trying to update the solver defaults in Firedrake to use LU if nothing else is specified. We also change the default SNES linesearch.

This changes the convergence of a taylor test in `test_hessian.py::test_dirichlet`. I can recover it with:

```
diff --git a/tests/firedrake_adjoint/test_hessian.py b/tests/firedrake_adjoint/test_hessian.py
index e771462..5a581a9 100644
--- a/tests/firedrake_adjoint/test_hessian.py
+++ b/tests/firedrake_adjoint/test_hessian.py
@@ -189,7 +189,7 @@ def test_dirichlet():
     bc = DirichletBC(V, c, "on_boundary")
 
     F = inner(grad(u), grad(v)) * dx + u**4*v*dx - f**2 * v * dx
-    solve(F == 0, u, bc)
+    solve(F == 0, u, bc, solver_parameters={"snes_rtol": 1e-10})
 
     J = assemble(u ** 4 * dx)
     Jhat = ReducedFunctional(J, Control(c))
```

Can someone apply this (I would prepare a PR but don't have access since the migration to github).

**Comment by stephankramer** [comment]
Hm, didn't mean to push that straight to master! Sorry about that, I think it's right anyway :crossed_fingers: 
 @funsim @sebastkm: should we restrict pushing straight to master?

**Comment by funsim** [comment]
Thanks Stephan. @sebastkm what is your preference regarding master pushes? The project doesn't get that many commits right now, so I don't have a strong opinion.

**Comment by sebastkm** [comment]
I'm fine with making master a protected branch.
