### ISSUE TITLE
Assigning AdjFloat to Constant leads to incompatible adj_value

### ISSUE THREAD

**Issue by stephankramer** [dolfin-adjoint/pyadjoint#34]
Consider the following code:
```
af=AdjFloat(0.1)
uc=Constant(0.0)
uc.assign(af)
mesh=UnitSquareMesh(1,1)
V=FunctionSpace(mesh,"CG",1)
u=project(uc, V)
J=assemble(u*u*dx)
rf=ReducedFunctional(J, Control(af))
rf.derivative()
```
This fails in fenics_adjoint with:
```
TypeError: float() argument must be a string or a number, not 'dolfin.cpp.la.Vector'
```
and similar in firedrake_adjoint. The reason is that the AdjFloat control end up with an adj_value in the form of a length-1 Vector. This is caused by the adjoint of the project creating such a Vector as the adjoint value of the Constant it depends on, and subsequently the assign simply copying this to be the adjoint value of the AdjFloat. What does work however is if you simply assign the Constant to the Function `u.assign(uc)`. In that case the adjoint value that is created for the Constant is just a float.

So the question is: should the adj_value of a Constant 1) be a Vector (obtained from the vector of its representation as a function in R functionspace) or should the adj_value simply 2) be a float?

In the case of 1) we should fix both Function assign when it assigns a Constant to a Function, to create a Vector adj_value on the Constant, and the Constant Assign when it assigns an AdjFloat to a Constant to convert that Vector back to a float for the adj_value of the AdjFloat.
In the case of 2) we need to fix SolveBlock and AssembleBlock which are currently creating Vector adj_values for Constants.

Happy to fix myself - but I'd like to hear your opinion on the question above...

**Comment by sebastkm** [comment]
The adj_value for Constants should be a Vector based on the R function space. Early on we just used floats, but when we introduced support for vector-valued constants we changed to vectors (which also made Constants a bit easier to work with as they could be handled in the same way as Functions). 

I'm not sure if the assign bug is something left over from before vector-valued constants were supported, but yes I agree that we should fix it according to 1).
