### ISSUE TITLE
Getting the adjoint variable

### ISSUE THREAD

**Issue by jacobmerson** [dolfin-adjoint/pyadjoint#35]
I apologize for this somewhat basic question. Is it possible to use dolfin-adjoint to get the adjoint variable? I understand how to get the derivatives of the functional, but I cannot find any reference to getting the adjoint variable’s value?.

Thanks for your help!

**Comment by sebastkm** [comment]
Take a look at the answer in issue #28 

The basic idea are callbacks supplied to the solve function that provides you with the adjoint solution when it is solved.

**Comment by jacobmerson** [comment]
@sebastkm 

Thanks for the help! I was able to get this working.
