### ISSUE TITLE
"Excesive" execution time in a demo file

### ISSUE THREAD

**Issue by ar-valdez** [dolfin-adjoint/pyadjoint#45]
I have been trying to run the next sample file [link](https://github.com/dolfin-adjoint/pyadjoint/blob/master/examples/poisson-topology/poisson-topology.py)...

I have "changed" the size of the problem by setting the number of fem partitions to 64 (default was 250)...

I am running using 4 cores (as the default execution call)...... It's been 11 hours and still nothing...

Does anybody gets better performance?

**Comment by sebastkm** [comment]
Hi, could you try running the script in serial? 
How have you installed IPOPT? I don't think IPOPT works in parallel in the pyadjoint docker images.

**Comment by ar-valdez** [comment]
Dear @sebastkm,

Thanks for the reply. I will try the suggestion, (Serial execution) and let you know the outcome....

Just in case, I have installed everything in anaconda, not on docker.

**Comment by ar-valdez** [comment]
Dear @sebastkm,

I have done what you suggested. Everything is working as expected. You can close the issue.

Let use this conversation thread to ask something else: I have been trying to use [multiphenics](https://gitlab.com/multiphenics/multiphenics), to solve "Elasticity with interfaces, imposing with Lagrange multipliers continuity"

I have been facing data structure problems when replacing the "forward(rho)" routines with the multi-block structure coming from multiphenics...

Do you have any recommendations, concerning the data structure, of the forward() routine's output?

I will keep updated...

**Comment by sebastkm** [comment]
I haven't used multiphenics, but after looking quickly at it, it does not seem like dolfin-adjoint will work with multiphenics out of the box.
