### ISSUE TITLE
ReadTheDocs compilation is failing.

### ISSUE THREAD

**Issue by funsim** [dolfin-adjoint/pyadjoint#49]
See image below:

![image](https://user-images.githubusercontent.com/763150/109053116-a8b13300-76dc-11eb-87b5-4b1f20120405.png)

**Comment by dham** [comment]
This is a sphinx extension update. You need to add a line similar to the following to `conf.py`
```
#  -- Options for sphinxcontrib.bibtex ------------------------------------
bibtex_bibfiles = ['demos/demo_references.bib', '_static/bibliography.bib', '_static/firedrake-apps.bib']
```
