### ISSUE TITLE
 FunctionAssigner does not work with annotate = False 

### ISSUE THREAD

**Issue by diego-hayashi** [dolfin-adjoint/pyadjoint#52]
FunctionAssigner does not work with annotate = False. The error is that “outputs“ is not defined. This issue can be easily noticed from the source  code ([https://github.com/dolfin-adjoint/pyadjoint/blob/master/fenics_adjoint/types/function_assigner.py](https://github.com/dolfin-adjoint/pyadjoint/blob/master/fenics_adjoint/types/function_assigner.py)).

**Comment by sebastkm** [comment]
Hi,

Thanks for reporting the bug. It should be resolved in PR #56
