### ISSUE TITLE
New solver parameters interface fails with LinearVariationalProblem

### ISSUE THREAD

**Issue by salazardetroya** [dolfin-adjoint/pyadjoint#6]
The following code fails because the solver parameters are never passed to the adjoint solve

```python
from firedrake import *
from firedrake_adjoint import *

def main():

    mesh = UnitSquareMesh(100, 100)

    parameters = {
        "mat_type" : "aij",
        "ksp_type" : "preonly",
        "ksp_monitor_true_residual": None,
        "pc_type" : "lu",
        "pc_factor_mat_solver_type" : "mumps"
        }

    P2 = VectorElement("CG", mesh.ufl_cell(), 2)
    P1 = FiniteElement("CG", mesh.ufl_cell(), 1)
    TH = P2*P1
    W = FunctionSpace(mesh, TH)

    U = TrialFunction(W)
    u, p = split(U)
    V = TestFunction(W)
    v, q = split(V)

    a = (inner(grad(u), grad(v)) - div(v)*p - q*div(u))*dx
    bcs = [DirichletBC(W.sub(0), Constant((1, 0)), (4,)),
       DirichletBC(W.sub(0), Constant((0, 0)), (1, 2, 3))]

    U1 = Function(W)
    f = Function(W).project(as_vector([1.0, 1.0, 0.0]), annotate=False)
    L = inner(f, V)*dx(domain=mesh)
    problem = LinearVariationalProblem(a, L, U1, bcs=bcs)
    nullspace = MixedVectorSpaceBasis(W, [W.sub(0), VectorSpaceBasis(constant=True)])
    solver_stokes1 = LinearVariationalSolver(problem, solver_parameters=parameters, nullspace=nullspace)
    solver_stokes1.solve()

    u1, p1 = split(U1)
    J = assemble(u1[0]*dx)
    Jhat = ReducedFunctional(J, Control(f))
    valor = Jhat(f)
    Jhat.derivative()

if __name__ == '__main__':
    main()
```

Looking at the changes in the code, it seems as if the solver parameters need to be passed to `LinearVariationalSolver.solve()`, but Firedrake does not accept certain parameters in this function. Maybe it could be solved by passing the solver parameters and adding these parameters to the list of `pop_kwargs_keys` in `GenericSolveBlock`. I am not sure about what the right implementation is, but I am willing to write it if given indications.

If I pass `forward_kwargs` to `LinearVariationalSolver.solve()` as in 
```python
solver_stokes1.solve(forward_kwargs={"solver_parameters" : parameters})
```
then `mat_type` is never passed and the direct solver cannot solve the system with a matrix type nest (default in Firedrake).

**Comment by dham** [comment]
Is this on master or on the `self_adjoint` branches? We're about to merge a significant refactoring of firedrake-adjoint, so I'm keen to know if this is still an issue post-merge.

**Comment by sebastkm** [comment]
I believe the issue is present on both master and self_adjoint. It shouldn't be too difficult to fix after merge, its just that I did (and still do not) know enough about the firedrake solver interface.

**Comment by salazardetroya** [comment]
@sebastkm  now that `self_adjoint` is merged, do you mind if I give it a shot to this issue? Or you had some thing in mind?

**Comment by sebastkm** [comment]
@salazardetroya I didn't plan anything so you could give it a try, thanks!
I would prefer if firedrake specific changes made their way into the firedrake repo:
https://github.com/firedrakeproject/firedrake/tree/master/firedrake/adjoint

**Comment by florianwechsung** [comment]
@salazardetroya Have you had time to make the required changes in firedrake? I'm running into the same issue.

**Comment by salazardetroya** [comment]
@florianwechsung I have not, as it is not a priority for me at this time. Feel free of making the changes if you need them asap.

**Comment by florianwechsung** [comment]
This diff in firedrake fixes the issue for me and all tests in pyadjoint still pass.

```
diff --git a/firedrake/adjoint/blocks.py b/firedrake/adjoint/blocks.py
index 84e15edd..c68b88bb 100644
--- a/firedrake/adjoint/blocks.py
+++ b/firedrake/adjoint/blocks.py
@@ -104,7 +104,7 @@ class NonlinearVariationalSolveBlock(GenericSolveBlock):
         self.solver_params = solver_params.copy()
         self.solver_kwargs = solver_kwargs

-        super().__init__(lhs, rhs, func, bcs, **kwargs)
+        super().__init__(lhs, rhs, func, bcs, **{**solver_kwargs,**kwargs})

         if self.problem_J is not None:
             for coeff in self.problem_J.coefficients():
```

I don't know the inner workings of pyadjoint well enough to see if this might wreak havoc somewhere else. @dham @sebastkm @nbouziani , any objections to this change?

**Comment by salazardetroya** [comment]
@florianwechsung thanks a lot for the patch. It works pretty well for me. Could you submit the PR in the firedrake repo?
