### ISSUE TITLE
No recent release

### ISSUE THREAD

**Issue by DiffeoInvariant** [dolfin-adjoint/pyadjoint#60]
Hi pyadjoint devs,

We (the [CRIKit](https://crikit.science) team) are preparing to release CRIKit, and we're running into an issue with the fact that there hasn't been a pyadjoint release since mid-2019. Specifically, PyPI does not allow so-called "direct dependencies", which are dependencies like git repositories. We need the latest pyadjoint development for CRIKit to work, so we've been installing via `"dolfin_adjoint @ git+https://github.com/dolfin-adjoint/pyadjoint.git@master"` (in the `install_requires` in our `setup.py`), but we can't do that for the PyPI upload. 

Would it be possible to create another release of pyadjoint with the latest updates?

**Comment by sebastkm** [comment]
Hi,

CRIKit seems very interesting, I will have to check it out.

We will be making another release soon. I would hope to merge most (or all) of the current pull requests first.
But perhaps we should just make a PyPI release without them and opt for more frequent releases on PyPI.

**Comment by DiffeoInvariant** [comment]
Hi Sebastian, 

Excellent, that's great to hear! From our perspective, more frequent releases of Pyadjoint on PyPI would be awesome, and would make things much easier for us. 

We have been considering the possibility of maintaining our own fork of this repo, which would be more effort for us and would make it harder to upstream our development to Pyadjoint itself if/when any particular components are ready to do so* as compared to using Pyadjoint/the `dolfin_adjoint`/`fenics_adjoint` in this repo as a dependency, but more frequent releases of Pyadjoint to PyPI would make this issue entirely moot. Thank you!

Our code is hosted at https://gitlab.com/crikit/crikit if you're curious.

* we have a *slightly* different approach to AD that relies on the adjoint, TLM, and hessian functions returning the appropriate VJP/JVP/HVP as a function of `inputs`, `tlm_inputs`/`adj_inputs`, etc. instead of just updating the values of the block variables and not returning anything, as well as functions for computing Jacobian matrices, but if you/the other Pyadjoint devs are interested in upstreaming, e.g. our JAX work when it's complete (we don't have Hessian support yet, and assembling forms that contain JAX or other non-FEniCS functions is still a little awkward), we'd be happy to work with you on that
 
(CC @gbruer15 @jedbrown)

**Comment by sebastkm** [comment]
I've now uploaded a version 2019.1.1 to PyPI.

I also took a look at your repository and saw that you have made some additions to pyadjoint. I wonder if you think some of these would be good to merge into pyadjoint?
We are open to pull requests and also to suggestions for what we could change to make pyadjoint nicer to work with.

**Comment by DiffeoInvariant** [comment]
Thank you! We'll probably be releasing CRIKit to PyPI very soon now.

Yes, we definitely would like to upstream some of our changes to pyadjoint. Of the additions you've seen, are there any in particular that you'd like to see in pyadjoint? I would personally like to upstream the `JAXBlock`/`overload_jax` eventually, but I see several issues with that as it exists right now:

1. I don't have Hessian-vector products working right now (probably could get them working without *too* much trouble though), just adjoint, TLM, and TLM matrix functions
2. To use JAX or TensorFlow inside of a FEniCS PDE, right now you need to use `crikit.assemble_with_cr()` instead of `fenics_adjoint.assemble()`, and you need a `pyadjoint_utils.SNESSolver` to solve the equation (instead of a `fenics_adjoint.NonlinearVariationalSolver` ). I would personally like to get something more like @nbouziani 's `ExternalOperator` class working so we can use the `fenics_adjoint` solvers to solve variational problems with the normal `assemble()` for assembly.

Some things from `pyadjoint_utils` that are (IMO) ready to upstream with minimal changes:

1. `ReducedFunction` (like `ReducedFunctional`, but the output might not be an `AdjFloat`, just some generic `OverloadedType`).
2. Jacobian matrix computing functions (`Tape.evaluate_tlm_matrix()` and `Block.evaluate_tlm_matrix_component()`)

**Comment by nbouziani** [comment]
@DiffeoInvariant Regarding the use of JAX or TensorFlow, this can indeed be done with ExternalOperator. External operators are annotated and they have their own blocks.

So when you call `assemble` or `solve` the `Assemble/GenericSolveBlock` will use the ExternalOperator subclass representing your operator to compute the bit needed.

(CC @dham)

**Comment by sebastkm** [comment]
@DiffeoInvariant 
`ReducedFunction` is something that has been in different branches for a very long time, with even an open pull request https://bitbucket.org/dolfin-adjoint/pyadjoint/pull-requests/92.
I would definitely like for some `ReducedFunction` implementation to be merged into master.

Having an interface for computing Jacobian matrices is also welcome.

**Comment by DiffeoInvariant** [comment]
@sebastkm Great, thanks! That PR that Toby wrote is the same `ReducedFunction` he wrote for CRIKit (I didn't realize he had an open PR here), so we can get that updated and ready to go soon, hopefully in the next few weeks.
