### ISSUE TITLE
Error in custom function example normalise.py (modifies input func)

### ISSUE THREAD

**Issue by mulbrich** [dolfin-adjoint/pyadjoint#73]
Hi,

when I experimented with custom functions and overloading, I noticed what
I would consider a bug in pyadjoint/docs/source/_static/overloading/normalise.py:

The function

def normalise(func):
    vec = func.vector()
    vec /= vec.norm('l2')
    return Function(func.function_space(), vec)

modifies the input func, thus normalising it as well, since func.vector()
is modified without first making a deep copy.
This can have side effects:

If the input f to normalize(f) is reused after the call, e.g., if we modify
tutorial9_overloading.py as follows

g = normalise(f)

J = assemble((g+f)*dx)

then the Taylor test fails:

Running Taylor test
Computed residuals: [0.002464839972388524, 0.0011515521177464082, 0.000555068990161312, 0.0002722974398862185]
Computed convergence rates: [1.097914276807522, 1.0528407051626965, 1.0274836784598766]

This problem is not visible in the original tutorial9_overloading.py since
there only g is used after calling normalise, but not f:

J = assemble(g*dx)

Thus, I think normalise() should be changed to either

def normalise(func):
    vec = func.vector().copy()
    vec /= vec.norm('l2')
    return Function(func.function_space(), vec)

or

def normalise(func):
    vec = func.vector()
    return Function(func.function_space(), vec/vec.norm('l2'))

Best,

Michael

**Comment by sebastkm** [comment]
Hi Michael,

Thanks for reporting this error. I have made a pull request with the fix.

**Comment by mulbrich** [comment]
Many thanks, Sebastian.

**Comment by jorgensd** [comment]
Fixed in https://github.com/dolfin-adjoint/pyadjoint/pull/74
